-- Migration 001: Initial schema for Supabase (PostgreSQL)
-- Mirrors the SQLite schema in core/storage.py.
-- Run this once in your Supabase SQL editor when migrating from git-based SQLite.

-- Job workflow status
CREATE TABLE IF NOT EXISTS job_status (
    uuid        UUID PRIMARY KEY,
    status      TEXT NOT NULL DEFAULT 'new'
                    CHECK (status IN ('new', 'interesting', 'applied')),
    notes       TEXT,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_job_status_status
    ON job_status (status);

-- Generated DOCX documents linked to a job
CREATE TABLE IF NOT EXISTS documents (
    id            BIGSERIAL PRIMARY KEY,
    job_uuid      UUID NOT NULL REFERENCES job_status(uuid) ON DELETE CASCADE,
    doc_type      TEXT NOT NULL CHECK (doc_type IN ('cv', 'cover_letter')),
    file_path     TEXT NOT NULL,
    country_style TEXT NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_documents_job_uuid
    ON documents (job_uuid);

-- Migration notes:
-- 1. TEXT → UUID: job identifiers are UUIDs (generated by pipeline/processor.py).
--    SQLite stores them as TEXT; Supabase uses the native UUID type.
-- 2. TEXT timestamps → TIMESTAMPTZ: SQLite stores datetimes as ISO strings;
--    Supabase uses timestamptz with automatic timezone handling.
-- 3. AUTOINCREMENT → BIGSERIAL: equivalent PostgreSQL sequence type.
-- 4. ON DELETE CASCADE on documents.job_uuid: if a job_status row is removed,
--    its documents are also removed automatically.
--
-- To migrate existing SQLite data:
--   1. Export SQLite to CSV: sqlite3 data/jobs.db ".headers on" ".mode csv" "SELECT * FROM job_status;" > job_status.csv
--   2. Import via Supabase dashboard → Table Editor → Import CSV
--   3. Repeat for documents table
